### ISSUE TITLE
손가영 백엔드 6주차 배포과제

### ISSUE THREAD

**Issue by gayo73** [likelion-Inha-12/gayo73#10]
1. 배포 성공
<img width="1470" alt="스크린샷 2024-05-17 오전 2 25 22" src="https://github.com/likelion-Inha-12/gayo73/assets/163620291/ce3cb9d6-c82e-4ce0-ba6d-5d7c72237537">

2. 인스턴스 정보
<img width="1470" alt="스크린샷 2024-05-17 오전 2 27 03" src="https://github.com/likelion-Inha-12/gayo73/assets/163620291/e46aee55-c947-48a6-a4d4-222f40ff42d0">

**Comment by gayo73** [comment]
![Uploading 스크린샷 2024-05-17 오전 2.27.03.png…]()

**Comment by juwon0403** [comment]
너무 기특한 아기사자!!!!!!
많은 시련과.. 역경이.. 있었던 만큼 해커톤에서는 수월하게 하실 수 있으실 거에요 ㅎㅎ

가영님 정말 정말 정말.. 고생 많으셨어요!!
