### ISSUE TITLE
손가영 백엔드 7주차 과제

### ISSUE THREAD

**Issue by gayo73** [likelion-Inha-12/gayo73#11]
https://mire-rake-093.notion.site/70241bd94f0f4ff8b464ffe90835b946?pvs=4
키워드 과제 노션 링크입니다.

**Comment by gayo73** [comment]
![Uploading 스크린샷 2024-05-22 오후 1.25.02.png…]()

**Comment by gayo73** [comment]
<img width="1436" alt="스크린샷 2024-05-22 오후 1 25 02" src="https://github.com/likelion-Inha-12/gayo73/assets/163620291/e7966726-d4e9-4125-88ee-b9f4110c3e32">

**Comment by juwon0403** [comment]
아주 깔끔하게 정리 잘해주셨어요!!!

단, 2가지만 수정하자면
1) 프로토콜의 예시로 http, https://를 들어주셨는데 프로토콜 뒤에 오는 **://**는 간단히 말하자면 URL에서 **구분자**의 역할을 하는 거라서, 정확하게 프로토콜만 찾으라고 한다면 http와 https만 말씀해주시면 됩니다!
2) 같은 출처 다른 출처 구분하는 표에서 3번의 http://lionz12.netlify.app/homework가 "호스트는 같지만 프로토콜은 다르다"는 건 맞지만, 포트는 같다고 볼 수 있어요! 문제에 제시된 http://lionz12.netlify.app과 3번에 제시된 http://lionz12.netlify.app/homework 두 URL 모두 같은 프로토콜(http)을 사용하고 있는데, 지정된 포트 번호는 보이지 않죠?? 이럴 경우 기본 포트 번호가 사용되어 두 URL은 http의 기본 포트인 80을 사용한다고 볼 수 있습니다~ => 즉, 포트 번호가 지정되어 있지 않다면 기본 포트(http의 기본 포트 번호는 80, https의 기본 포트 번호는 443)

이 부분은 다시 이해해주셨으면 하는 마음에서 좀 길게 적어봤고, 나머지 과제 부분은 완벽합니당
URL, origin, domain 관계에 대한 과제를 내드리면서 "도메인 ⊂ Origin ⊂ URL" <- 이 포함관계를 이해하셨으면,, 하는 마음이었는데 정리한 부분에 있어서 놀랐어요 ㅎㅎ

과제하느라 수고 많으셨습니다!!
